Repository ModerCore/Moder, pull requests merged in 2024-12, with the labels that each got.

#33 feat: 实现 Xaml 热重载
  Moder.Core/App.axaml.cs
  Moder.Core/Moder.Core.csproj
Labels: Feature

#35 Feat: 实现不同平台下的侧边栏文件树排序
  Moder.Core/App.axaml.cs
  Moder.Core/Infrastructure/FileSort/IFileSortComparer.cs
  Moder.Core/Infrastructure/FileSort/LinuxFileSortComparer.cs
  Moder.Core/Infrastructure/FileSort/WindowsFileSortComparer.cs
  Moder.Core/Moder.Core.csproj
  Moder.Core/ViewsModel/Menus/SideBarControlViewModel.cs
  Moder.Hosting/Moder.Hosting.csproj
  Moder.Language/Moder.Language.csproj
  Moder.sln
Labels: Feature

#36 Feat: 设置UI添加主题选择器
  Moder.Core/App.axaml
  Moder.Core/App.axaml.cs
  Moder.Core/Converters/EnumTypeToStringListConverter.cs
  Moder.Core/Extensions/EnumExtensions.cs
  Moder.Core/Resources/AppTheme.cs
  Moder.Core/Resources/AppThemeResource.axaml
  Moder.Core/Resources/AppThemeStyleSetter.axaml
  Moder.Core/Resources/ThemeMode.cs
  Moder.Core/Resources/ThemeVariants.cs
  Moder.Core/Views/Menus/AppInitializeControlView.axaml
  Moder.Core/Views/Menus/AppInitializeControlView.axaml.cs
  Moder.Core/ViewsModel/Menus/AppInitializeControlViewModel.cs
  Moder.Language/Strings/Resource.Designer.cs
  Moder.Language/Strings/Resource.en-US.resx
  Moder.Language/Strings/Resource.resx
Labels: Feature

#39 feat: App 主题选择持久化
  Moder.Core/App.axaml.cs
  Moder.Core/Services/Config/AppSettingService.cs
  Moder.Core/Views/Menus/AppInitializeControlView.axaml
  Moder.Core/Views/Menus/AppInitializeControlView.axaml.cs
Labels: Feature

#40 Feat: 实现文件树右键菜单
  Moder.Core/App.axaml.cs
  Moder.Core/Encodings.cs
  Moder.Core/Models/SystemFileItem.cs
  Moder.Core/Moder.Core.csproj
  Moder.Core/Services/FileNativeService/IFileNativeService.cs
  Moder.Core/Services/FileNativeService/LinuxFileNativeService.cs
  Moder.Core/Services/FileNativeService/WindowsFileNativeService.cs
  Moder.Core/Views/Menus/AppInitializeControlView.axaml.cs
  Moder.Core/Views/Menus/MainControlView.axaml.cs
  Moder.Core/Views/Menus/NotSupportInfoControlView.axaml.cs
  Moder.Core/Views/Menus/RenameFileControlView.axaml
  Moder.Core/Views/Menus/RenameFileControlView.axaml.cs
  Moder.Core/Views/Menus/SideBarControlView.axaml
  Moder.Core/Views/Menus/SideBarControlView.axaml.cs
  Moder.Core/ViewsModel/Menus/RenameFileControlViewModel.cs
  Moder.Language/Strings/Resource.Designer.cs
  Moder.Language/Strings/Resource.en-US.resx
  Moder.Language/Strings/Resource.resx
  Moder.sln.DotSettings
Labels: Feature, UI, CSharp, Localization

#42 Refactor: 使用模板控件重用路径选择器
  Moder.Core/App.axaml
  Moder.Core/Moder.Core.csproj
  Moder.Core/Views/Controls/DirectorySelector.axaml
  Moder.Core/Views/Controls/DirectorySelector.axaml.cs
  Moder.Core/Views/Menus/AppInitializeControlView.axaml
Labels: UI, CSharp, Refactor

#44 i18: 添加本地化文本
  Moder.Core/Models/SystemFileItem.cs
  Moder.Core/Services/FileNativeService/WindowsFileNativeService.cs
  Moder.Core/ViewsModel/Menus/AppInitializeControlViewModel.cs
  Moder.Language/Strings/Resource.Designer.cs
  Moder.Language/Strings/Resource.en-US.resx
  Moder.Language/Strings/Resource.resx
Labels: CSharp, Localization

#48 feat: 右键菜单添加复制路径功能
  Moder.Core/Infrastructure/ITabViewItem.cs
  Moder.Core/Infrastructure/Unit.cs
  Moder.Core/Messages/SelectedTraitChangedMessage.cs
  Moder.Core/Models/SystemFileItem.cs
  Moder.Core/Views/Menus/SideBarControlView.axaml
  Moder.Core/ViewsModel/Game/TraitSelectionWindowViewModel.cs
  Moder.Language/Strings/Resource.Designer.cs
  Moder.Language/Strings/Resource.en-US.resx
  Moder.Language/Strings/Resource.resx
Labels: Feature, UI, CSharp, Localization

#49 Feat: 启动时在后台加载本地化资源
  Moder.Core/App.axaml.cs
  Moder.Core/Views/Menus/AppInitializeControlView.axaml.cs
  Moder.Core/Views/Menus/MainControlView.axaml
  Moder.Core/Views/Menus/MainControlView.axaml.cs
  Moder.Core/Views/Menus/StatusBarControlView.axaml
  Moder.Core/Views/Menus/StatusBarControlView.axaml.cs
  Moder.Core/ViewsModel/Menus/StatusBarControlViewModel.cs
Labels: Feature, UI, CSharp

#50 Feat: 特质搜索支持搜索修饰符名称
  Moder.Core/Models/Vo/TraitVo.cs
  Moder.Core/Services/GameResources/Modifiers/ModifierService.cs
  Moder.Core/Views/Game/TraitSelectionWindowView.axaml
  Moder.Core/ViewsModel/Game/TraitSelectionWindowViewModel.cs
  Moder.Language/Strings/Resource.Designer.cs
  Moder.Language/Strings/Resource.en-US.resx
  Moder.Language/Strings/Resource.resx
Labels: Feature, UI, CSharp, Localization

#56 style(README):readme添加介绍与功能说明
  README.md
Labels: documentation

#57 style(README):readme添加介绍
  README.md
Labels: documentation

#58 Feat: 实现文本编辑器基本功能
  Moder.Core/Assets/CodeEditor/Grammars/yaml/cgmanifest.json
  Moder.Core/Assets/CodeEditor/Grammars/yaml/language-configuration.json
  Moder.Core/Assets/CodeEditor/Grammars/yaml/package.json
  Moder.Core/Assets/CodeEditor/Grammars/yaml/package.nls.json
  Moder.Core/Assets/CodeEditor/Grammars/yaml/syntaxes/yaml.tmLanguage.json
  Moder.Core/Controls/TextEditorControl.axaml
  Moder.Core/Controls/TextEditorControl.axaml.cs
  Moder.Core/Editor/ParadoxRegistryOptions.cs
  Moder.Core/Editor/ScopeNameTypes.cs
  Moder.Core/Infrastructure/ITabViewItem.cs
  Moder.Core/Services/TabViewNavigationService.cs
  Moder.Core/Views/Game/CharacterEditorControlView.axaml
  Moder.Core/Views/Game/CharacterEditorControlView.axaml.cs
  Moder.Core/Views/Game/FileEditorControlView.axaml
  Moder.Core/Views/Game/FileEditorControlView.axaml.cs
  Moder.Core/Views/Menus/AppSettingsView.axaml.cs
  Moder.Core/Views/Menus/SideBarControlView.axaml.cs
  Moder.Core/ViewsModel/Menus/SideBarControlViewModel.cs
Labels: Feature, UI, CSharp

#59 docs: 更新 Readme
  README.md
Labels: documentation
